### PR TITLE
Override uploader.js

### LINKED ISSUE #453: File Uploaded many small files fails
In ScholarSphere 3.0
When I create a new work
And I choose many (10 or more) small (15KB or less) files using add files or add folder
Then I get some blank lines where a file should be in the upload screen

### PR DESCRIPTION
**Pull request by awead**
Requires some rearranging of the javascript so we can limit concurrent uploads to only 1 file at a time.

This fixes #453 but it's not ideal. The ideal solution would be to have multiple concurrent uploads in our current deployment, however, I'm not sure if that possible give server setup, etc.

If you all are okay with this, we can merge. You can try it out on QA. It doesn't slow things down too much to do one file at a time. Let me know what you think: @cam156 @mtribone @olendorf

### CODE REVIEW

File: app/assets/javascripts/sufia/uploader.js [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+
+  $.fn.extend({
+    sufiaUploader: function( options ) {
+      // Initialize our jQuery File Upload widget.
+      // TODO: get these values from configuration.
+      this.fileupload($.extend({
+        // xhrFields: {withCredentials: true},              // to send cross-domain cookies
+        // acceptFileTypes: /(\.|\/)(png|mov|jpe?g|pdf)$/i, // not a strong check, just a regex on the filename
+        // limitMultiFileUploadSize: 500000000, // bytes
+        limitConcurrentUploads: 1,
```
Comment (carolyncole) [inline app/assets/javascripts/sufia/uploader.js:33]: @awead is this the line that makes all the difference?

File: app/assets/javascripts/application.js [hunk 2]
```diff
@@ -8,5 +8,9 @@
 // Required by Blacklight
 //= require blacklight/blacklight
 
-//= require_tree .
-//= require sufia
\ No newline at end of file
+//= require batch_edit
```
Comment (carolyncole) [inline app/assets/javascripts/application.js:12]: @awead is this removal of require_tree needed for the PR or just a preference?

**Review by carolyncole — CHANGES_REQUESTED** [review]
@awead The changes look ok.  Some comments either at the top or around the 1 to let us know what we changed and why would be nice.  We do not want to do a comparison a month or two from now and think we do not need this override.

File: app/assets/javascripts/application.js (hunk 2 above)
Comment (awead) [reply app/assets/javascripts/application.js:12]: @cam156 require_tree was causing all kinds of JS loading errors.

File: app/assets/javascripts/sufia/uploader.js (hunk 1 above)
Comment (awead) [reply app/assets/javascripts/sufia/uploader.js:33]: yep. I'll add a comment.
